#! /bin/sh

#picom -f --config $HOME/.config/picom/picom.conf &
picom --experimental-backends -f -b
#launch shortchuts
pgrep -x sxhkd > /dev/null || sxhkd &

#set bg wallpaper
feh -F ~/wallpapers/poggers19.jpg &

sleep 5
#launch polybar
#$HOME/.config/polybar/launch.sh

#polybar example &
# set laptop trackpad settings
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Natural Scrolling Enabled" 1

bspc monitor -d I II III IV V

bspc config border_width         0.4
bspc config window_gap          16
bspc config focused_border_color  "#FFE227"
bspc config normal_border_color "#aaFFFFFF"

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/colorblocks/launch.sh	
